feature_labels = ['min', '10th_percentile','median','90th_percentile','max', 'mean', 'st_dev', 'sum', 'area', 
                  'b1_max', 'b1_mean', 'b1_std', 'b1_median', 'b1_sum', 'b1_10th', 'b1_90th',
                  'b2_max', 'b2_mean', 'b2_std', 'b2_median', 'b2_sum', 'b2_10th', 'b2_90th',
                  'b3_max', 'b3_mean', 'b3_std', 'b3_median', 'b3_sum', 'b3_10th', 'b3_90th', 
                  'b4_max', 'b4_mean', 'b4_std', 'b4_median', 'b4_sum', 'b4_10th', 'b4_90th',
                  'b5_max', 'b5_mean', 'b5_std', 'b5_median', 'b5_sum', 'b5_10th', 'b5_90th',
                  'b6_max', 'b6_mean', 'b6_std', 'b6_median', 'b6_sum', 'b6_10th', 'b6_90th',
                  'b7_max', 'b7_mean', 'b7_std', 'b7_median', 'b7_sum', 'b7_10th', 'b7_90th',
                  'b8_max', 'b8_mean', 'b8_std', 'b8_median', 'b8_sum', 'b8_10th', 'b8_90th',
                  'b9_max', 'b9_mean', 'b9_std', 'b9_median', 'b9_sum', 'b9_10th', 'b9_90th',
                  'b10_max', 'b10_mean', 'b10_std', 'b10_median', 'b10_sum', 'b10_10th', 'b10_90th',
                  'b11_max', 'b11_mean', 'b11_std', 'b11_median', 'b11_sum', 'b11_10th', 'b11_90th',
                  'ndvi_jan_max', 'ndvi_jan_mean', 'ndvi_jan_std', 'ndvi_jan_median', 'ndvi_jan_sum', 'ndvi_jan_10th', 'ndvi_jan_90th',
                  'ndvi_feb_max', 'ndvi_feb_mean', 'ndvi_feb_std', 'ndvi_feb_median', 'ndvi_feb_sum', 'ndvi_feb_10th', 'ndvi_feb_90th',
                  'ndvi_mar_max', 'ndvi_mar_mean', 'ndvi_mar_std', 'ndvi_mar_median', 'ndvi_mar_sum', 'ndvi_mar_10th', 'ndvi_mar_90th',
                  'ndvi_apr_max', 'ndvi_apr_mean',  'ndvi_apr_std', 'ndvi_apr_median', 'ndvi_apr_sum', 'ndvi_apr_10th', 'ndvi_apr_90th',
                  'ndvi_may_max', 'ndvi_may_mean', 'ndvi_may_std', 'ndvi_may_median', 'ndvi_may_sum', 'ndvi_may_10th', 'ndvi_may_90th',
                  'ndvi_jun_max','ndvi_jun_mean', 'ndvi_jun_std', 'ndvi_jun_median', 'ndvi_jun_sum', 'ndvi_jun_10th', 'ndvi_jun_90th',
                  'ndvi_jul_max', 'ndvi_jul_mean', 'ndvi_jul_std', 'ndvi_jul_median', 'ndvi_jul_sum', 'ndvi_jul_10th', 'ndvi_jul_90th',
                  'ndvi_aug_max', 'ndvi_aug_mean', 'ndvi_aug_std', 'ndvi_aug_median', 'ndvi_aug_sum', 'ndvi_aug_10th', 'ndvi_aug_90th',
                  'ndvi_sep_max', 'ndvi_sep_mean', 'ndvi_sep_std', 'ndvi_sep_median', 'ndvi_sep_sum', 'ndvi_sep_10th', 'ndvi_sep_90th',
                  'ndvi_oct_max', 'ndvi_oct_mean',  'ndvi_oct_std', 'ndvi_oct_median', 'ndvi_oct_sum', 'ndvi_oct_10th', 'ndvi_oct_90th',
                  'ndvi_nov_max', 'ndvi_nov_mean', 'ndvi_nov_std', 'ndvi_nov_median', 'ndvi_nov_sum', 'ndvi_nov_10th', 'ndvi_nov_90th',
                  'ndvi_dec_max', 'ndvi_dec_mean', 'ndvi_dec_std', 'ndvi_dec_median', 'ndvi_dec_sum', 'ndvi_dec_10th', 'ndvi_dec_90th',
                  'green_jan_max', 'green_jan_mean', 'green_jan_std', 'green_jan_median', 'green_jan_sum', 'green_jan_10th', 'green_jan_90th',
                  'green_feb_max', 'green_feb_mean', 'green_feb_std', 'green_feb_median', 'green_feb_sum', 'green_feb_10th', 'green_feb_90th',
                  'green_mar_max', 'green_mar_mean', 'green_mar_std', 'green_mar_median', 'green_mar_sum', 'green_mar_10th', 'green_mar_90th',
                  'green_apr_max', 'green_apr_mean',  'green_apr_std', 'green_apr_median', 'green_apr_sum', 'green_apr_10th', 'green_apr_90th',
                  'green_may_max', 'green_may_mean', 'green_may_std', 'green_may_median', 'green_may_sum', 'green_may_10th', 'green_may_90th',
                  'green_jun_max','green_jun_mean', 'green_jun_std', 'green_jun_median', 'green_jun_sum', 'green_jun_10th', 'green_jun_90th',
                  'green_jul_max', 'green_jul_mean', 'green_jul_std', 'green_jul_median', 'green_jul_sum', 'green_jul_10th', 'green_jul_90th',
                  'green_aug_max', 'green_aug_mean', 'green_aug_std', 'green_aug_median', 'green_aug_sum', 'green_aug_10th', 'green_aug_90th',
                  'green_sep_max', 'green_sep_mean', 'green_sep_std', 'green_sep_median', 'green_sep_sum', 'green_sep_10th', 'green_sep_90th',
                  'green_oct_max', 'green_oct_mean',  'green_oct_std', 'green_oct_median', 'green_oct_sum', 'green_oct_10th', 'green_oct_90th',
                  'green_nov_max', 'green_nov_mean', 'green_nov_std', 'green_nov_median', 'green_nov_sum', 'green_nov_10th', 'green_nov_90th',
                  'green_dec_max', 'green_dec_mean', 'green_dec_std', 'green_dec_median', 'green_dec_sum', 'green_dec_10th', 'green_dec_90th',
                  'rain_jan_max', 'rain_jan_mean', 'rain_jan_std', 'rain_jan_median', 'rain_jan_sum', 'rain_jan_10th', 'rain_jan_90th',
                  'rain_feb_max', 'rain_feb_mean', 'rain_feb_std', 'rain_feb_median', 'rain_feb_sum', 'rain_feb_10th', 'rain_feb_90th',
                  'rain_mar_max', 'rain_mar_mean', 'rain_mar_std', 'rain_mar_median', 'rain_mar_sum', 'rain_mar_10th', 'rain_mar_90th',
                  'rain_apr_max', 'rain_apr_mean',  'rain_apr_std', 'rain_apr_median', 'rain_apr_sum', 'rain_apr_10th', 'rain_apr_90th',
                  'rain_may_max', 'rain_may_mean', 'rain_may_std', 'rain_may_median', 'rain_may_sum', 'rain_may_10th', 'rain_may_90th',
                  'rain_jun_max','rain_jun_mean', 'rain_jun_std', 'rain_jun_median', 'rain_jun_sum', 'rain_jun_10th', 'rain_jun_90th',
                  'rain_jul_max', 'rain_jul_mean', 'rain_jul_std', 'rain_jul_median', 'rain_jul_sum', 'rain_jul_10th', 'rain_jul_90th',
                  'rain_aug_max', 'rain_aug_mean', 'rain_aug_std', 'rain_aug_median', 'rain_aug_sum', 'rain_aug_10th', 'rain_aug_90th',
                  'rain_sep_max', 'rain_sep_mean', 'rain_sep_std', 'rain_sep_median', 'rain_sep_sum', 'rain_sep_10th', 'rain_sep_90th',
                  'rain_oct_max', 'rain_oct_mean',  'rain_oct_std', 'rain_oct_median', 'rain_oct_sum', 'rain_oct_10th', 'rain_oct_90th',
                  'rain_nov_max', 'rain_nov_mean', 'rain_nov_std', 'rain_nov_median', 'rain_nov_sum', 'rain_nov_10th', 'rain_nov_90th',
                  'rain_dec_max', 'rain_dec_mean', 'rain_dec_std', 'rain_dec_median', 'rain_dec_sum', 'rain_dec_10th', 'rain_dec_90th']
